### ISSUE TITLE
建议：提供开箱即用的部署支持，将会吸引更多新用户尝试【已提供开箱配置，详情见 readme 开箱配置示例】

### ISSUE THREAD

**Issue by gittosuperfly** [LetTTGACO/elog#10]
虽然通过一些配置可做到 Notion编辑->自动拉取->自动更新，但是这个配置的过程依然会耗费一些时间，以及有一定的学习门槛。这阻止了很多想先浅尝一下的用户。

可以参考NotionNext的配置方式：直接 github fork 模版仓库->连接到一个新的 Vercel，配置一下id到环境变量即可直接使用。只需点两三下按钮，非常快速且方便。

**Comment by LetTTGACO** [comment]
> 虽然通过一些配置可做到 Notion编辑->自动拉取->自动更新，但是这个配置的过程依然会耗费一些时间，以及有一定的学习门槛。这阻止了很多想先浅尝一下的用户。
> 
> 可以参考NotionNext的配置方式：直接 github fork 模版仓库->连接到一个新的 Vercel，配置一下id到环境变量即可直接使用。只需点两三下按钮，非常快速且方便。

不错的建议，安排安排

**Comment by happyzhangyyds** [comment]
期待作者大大！

**Comment by jaychoubaby** [comment]
期待开箱即用

**Comment by DerickIT** [comment]
期待早日实现开箱即用

**Comment by LetTTGACO** [comment]
开箱即用示例：
10 分钟搭建自动化博客
[Notion + Hexo + GitHub Actions + Vercel 博客解决方案](https://github.com/elog-x/notion-hexo)
