### ISSUE TITLE
yuque支持公式 latex导出

### ISSUE THREAD

**Issue by vva1024** [LetTTGACO/elog#105]
### 你当前使用的Elog版本

0.14.2

### 描述一下此特性

目前默认是将公式导出为图片，修改以下行是否可以支持公式为latex格式导出？希望可以开放成一个选项到配置文件中。

https://github.com/LetTTGACO/elog/blob/b3530338afd4d736070ca57f91cacddb5bd9aa4d/packages/sdk-yuque/src/pwd/client.ts#L158

https://github.com/LetTTGACO/elog/blob/b3530338afd4d736070ca57f91cacddb5bd9aa4d/packages/sdk-yuque/src/pwd/client.ts#L159

**Comment by LetTTGACO** [comment]
不支持的，语雀官方 api 返回给我的就是图片。他没有给我原始的公式表达式。
语雀的 md 导出是高度封装过的，他是直接返回给我的 md 字符，无法过多的定制化。其他平台返回是最原始的数据，可以进一步定制化

**Comment by LetTTGACO** [comment]
你没理解错。
不过我需要确认一下这个选项在 api 中是否存在，如果可以的话我会尽快加上，感谢提供线索

**Comment by LetTTGACO** [comment]
我刚试了下看了下是支持的！
你给出的代码标注非常有效，我一开始是在手机上看的 issue，并未仔细看你标注的代码，这里说声抱歉。

预计明天会更新！感谢反馈！

**Comment by LetTTGACO** [comment]
已升级，请升级到最新版即可

https://github.com/LetTTGACO/elog/releases/tag/v0.14.3
