### ISSUE TITLE
点赞

### ISSUE THREAD

**Issue by vannvan** [LetTTGACO/elog#11]
通过阮一峰博客看到作者的项目，我在使用语雀的时候也有类似的想法，借助一个成熟的软件实现跨平台数据同步，不过目前只做了语雀的导出。语雀的token权限从一开始的普通用户到专业会员用户再到现在的超级会员才有，虽然我也是深度使用者但觉得他格局越来越小了。
所以我自己开发了一个无需token的导出工具，看作者要不要考虑一下我的思路，同时采用语雀自己的导出操作可以很好的解决https://github.com/LetTTGACO/elog/issues/6 这个问题。

https://github.com/vannvan/yuque-tools

**Comment by LetTTGACO** [comment]
> 通过阮一峰博客看到作者的项目，我在使用语雀的时候也有类似的想法，借助一个成熟的软件实现跨平台数据同步，不过目前只做了语雀的导出。语雀的token权限从一开始的普通用户到专业会员用户再到现在的超级会员才有，虽然我也是深度使用者但觉得他格局越来越小了。 所以我自己开发了一个无需token的导出工具，看作者要不要考虑一下我的思路，同时采用语雀自己的导出操作可以很好的解决#6 这个问题。
> 
> https://github.com/vannvan/yuque-tools

确实是一个非常好的办法，可以绕过语雀token。我研究一下，也非常欢迎你参与建设Elog

**Comment by LetTTGACO** [comment]
现已支持语雀账号密码方式导出md文档，非常感谢你的项目
