### ISSUE TITLE
开启按目录存放文档，使用命令清除缓存时，无法清除目录里的文档

### ISSUE THREAD

**Issue by QoneFeng** [LetTTGACO/elog#18]
当开启了deploy.local.catalog=true时，文档已经按目录创建存放了。但是在npx @elog/cli clean时，命令提示清空了缓存、图片、文档。可是目录的文档还在

**Comment by LetTTGACO** [comment]
<img width="635" alt="image" src="https://github.com/LetTTGACO/elog/assets/37357188/77522689-10d1-44fc-8d1b-5beb33575085">
是不是像上面这样提示的
需要确认上面清理日志里的路径和你本地的路径是否一致

**Comment by QoneFeng** [comment]
这样的，我图片是清空了，缓存也被清空了，但文章还在
![image](https://github.com/LetTTGACO/elog/assets/1499678/1f6837d5-8744-4a3e-99f3-5321faf84257)

**Comment by LetTTGACO** [comment]
你这个情况比较特殊。
感觉你是想把文档放在yys下面，那就将`.elog.env`和`.elog/config.js`放在上一层文件夹，也就是和package.json同级，然后在`.elog/config.js`中指定`deploy.local.outputDir `字段设置为`./yys`，图片输出路径也加上`./yys`前缀，然后在`.elog/config.js`所在的文件夹中运行 sync 命令就行了。

**Comment by QoneFeng** [comment]
刚刚试了也还是不行，asset里面的图片是删了，但2022/2023这两个文件夹的内容还在
![image](https://github.com/LetTTGACO/elog/assets/1499678/50225a7d-e17c-4cae-b1bd-7abf5a43114f)
![image](https://github.com/LetTTGACO/elog/assets/1499678/f3f465f0-f255-49be-81f9-74346baa6b7e)
![image](https://github.com/LetTTGACO/elog/assets/1499678/64f29c43-7ab2-484c-b499-b00216708e56)

**Comment by LetTTGACO** [comment]
看了下删除文件夹使用的库：rimraf，顺便问了下 GPT，有可能是rimraf使用上有点问题，其实是因为其他原因删除失败了，但是我没判断，以为是删除成功了。需要你排查一下这个文件夹的权限问题
<img width="442" alt="image" src="https://github.com/LetTTGACO/elog/assets/37357188/90442218-871a-4ef5-8b1c-d71e9bebcb90">

![image](https://github.com/LetTTGACO/elog/assets/37357188/052cf6ee-9290-48fb-9a22-5e49b5388680)

或者试手动删除文件夹时 有没有提示权限等问题，按照 GPT 的提示看看

**Comment by LetTTGACO** [comment]
我尝试修正一下 API，你升级本地版本或使用npx测试版本试一下0.9.1-beta.0

npx @elog/cli@0.9.1-beta.0 clean

**Comment by QoneFeng** [comment]
![0AE6B008-A028-4775-A3F1-55096ED82E15](https://github.com/LetTTGACO/elog/assets/1499678/2275ceb5-ff39-4734-9ff2-e22abde4d2e9)

升级了本地版本，重新去试了删除，如何。最终文件夹还是没删。我手动删2022/2023，是没问题的
