### ISSUE TITLE
下载语雀文档时出错

### ISSUE THREAD

**Issue by BreakALegCml** [LetTTGACO/elog#35]
如图，刚开始下载就出错了，换了多个语雀的仓库也不行。

**Comment by BreakALegCml** [comment]
![Snipaste_2023-11-28_21-32-15](https://github.com/LetTTGACO/elog/assets/73064965/c0f88cc6-2280-4646-9b46-d4e3d131158e)

**Comment by LetTTGACO** [comment]
`deploy.local.filename`目前取值为 `title` 或者 `urlname`。
从错误来看，文档的`title`或者`urlname`不是一个字符串，所以报错了。
而这两个属性被复写的可能性有两个地方
1. 在语雀书写文档时，手动指定的 FrontMatter 中含有title或urlname，这将会覆盖文档自动生成的title或者urlname，并且该值不是一个字符串
2. 在 `deploy.local.formatExt`中，手动处理文档的`properties`字段时，将这俩字段进行了覆盖，有可能覆盖为空，有可能覆盖为非字符串。
你可以检查以上两种形式。

**Comment by BreakALegCml** [comment]
> 看起来是配置问题，贴一下 elog.config.js 中的deploy配置是怎么配置的

解决了，感谢。发现是自己的配置出了点问题！！
