### ISSUE TITLE
notion多行引用和多行callout渲染样式错误

### ISSUE THREAD

**Issue by zzzqu** [LetTTGACO/elog#42]
![Screenshot_2023-12-01-10-01-09-653_com android chrome](https://github.com/LetTTGACO/elog/assets/77374843/33924368-d8f5-43e8-a418-b9bad90da74b)
![Screenshot_2023-12-01-10-00-56-993_notion id](https://github.com/LetTTGACO/elog/assets/77374843/74293bae-4d9f-421f-8cfe-80b5551e131a)

**Comment by zzzqu** [comment]
![Screenshot_2023-12-01-10-08-13-894_com android chrome](https://github.com/LetTTGACO/elog/assets/77374843/c5b01816-c7cd-4101-8ca4-41395c8ded4f)

markdown源文件

**Comment by LetTTGACO** [comment]
你Elog的版本号是多少，elog.config.js 配置文件贴一下
我本地测试没问题
 notion文档：
 
![image](https://github.com/LetTTGACO/elog/assets/37357188/7b4c8a77-d990-4ca7-b487-33f64f9b923c)

markdown 文件
<img width="527" alt="image" src="https://github.com/LetTTGACO/elog/assets/37357188/8e53dca7-dd7d-4e2d-954f-586ecde76130">

**Comment by zzzqu** [comment]
elog版本：0.12.4
```
module.exports = {
  write: {
    platform: 'notion',
    notion: {
      token: process.env.NOTION_TOKEN,
      databaseId: process.env.NOTION_DATABASE_ID,
      filter: { property: 'status', select: { equals: '已发布' }}
    }
  },
  deploy: {
    platform: 'local',
    local: {
      outputDir: './source/_posts',
      filename: 'title',
      format: 'markdown',
      catalog: false,
      frontMatter: {
        enable: true,
        include: ['categories', 'tags', 'title', 'date', 'abbrlink', 'cover', 'description', 'typora-root-url'],
        timeFormat: true,
      },
      formatExt: './format-image.js',
    }
  },
  image: {
    enable: true,
    platform: 'local',
    local: {
      outputDir: './source/images/notion',
      prefixKey: './images/notion'
    }
  },
}
```

**Comment by LetTTGACO** [comment]
format-image.js 文件做了什么操作？
你是复制的我的 notion-hexo模版吗？有没有改动format-image.js中的信息

**Comment by LetTTGACO** [comment]
建议你调整一下 Notion 文档上这一块的文字，删除后重新书写试一下。
如果能稳定复现的话，可以将该页面公开分享给我，我试着复现一下

**Comment by zzzqu** [comment]
> 建议你调整一下 Notion 文档上这一块的文字，删除后重新书写试一下。 如果能稳定复现的话，可以将该页面公开分享给我，我试着复现一下

使用notion windows版本时用shift+enter引用换行，渲染正常；使用notion安卓版本时使用下面图示按钮实现引用换行，渲染错误。
![image](https://github.com/LetTTGACO/elog/assets/77374843/327d5b66-0827-4d70-b56b-efd41708f3d2)

**Comment by zzzqu** [comment]
两个方式使用notion自带导出后的markdown源文件区别
![image](https://github.com/LetTTGACO/elog/assets/77374843/b984997b-c146-47ad-becf-e1f190c9a808)
下面的样式会导致渲染错误。

**Comment by LetTTGACO** [comment]
这个按钮看起来不是换行，而是**缩进**。
如果是缩进的话，渲染后反而是正常的，只是客户端展示为换行。

感觉像是 Notion 的问题，你可以看一下在安卓手机上引用换行除了此方法，还有别的办法吗？

**Comment by LetTTGACO** [comment]
我试一下在Notion IOS手机上操作，这个就是缩进

https://github.com/LetTTGACO/elog/assets/37357188/78f7ccb9-a509-4ed3-be2a-7bc86100b199

**Comment by zzzqu** [comment]
> 这个按钮看起来不是换行，而是**缩进**。 如果是缩进的话，渲染后反而是正常的，只是客户端展示为换行。
> 
> 感觉像是 Notion 的问题，你可以看一下在安卓手机上引用换行除了此方法，还有别的办法吗？

确实是缩进，但可以实现引用换行，在notion里面样式是一样的，还未找到notion手机版的其他换行方式

**Comment by LetTTGACO** [comment]
我在 IOS上使用缩进也没办法换行，只是单纯的缩进，甚至在 IOS上无法实现引用内换行 😂。
那就是Notion 对安卓的缩进做了特殊处理，但是实际上接口返回的还是缩进，这个可能需要等 Notion 官方更新 API。
然后等 notion-to-md 这个库根据支持了。

**Comment by LetTTGACO** [comment]
如果没有其他疑问的话，我就关闭 issue 了
