### ISSUE TITLE
删除文章

### ISSUE THREAD

**Issue by zzzqu** [LetTTGACO/elog#49]
### 你当前使用的Elog版本

最新

### 描述一下此特性

在notion中删除文章，下一次构建时也能删除网站里的文章。

**Comment by LetTTGACO** [comment]
文档中有：https://elog.1874.cool/notion/bry3d3lwe206xuor#force-%E8%AF%B4%E6%98%8E

**Comment by LetTTGACO** [comment]
如果解决了你的问题，请关闭此 issue
