### ISSUE TITLE
建议: 增加快速列出文章发布状态的命令

### ISSUE THREAD

**Issue by Jason-Ma-0012** [LetTTGACO/elog#5]
我并不想发布草稿, 但语雀又没有明确的提示哪些文章已发布或未发布, 所以需要一个方式来快速查看文章状态

也许可以通过一个命令将文章状态输出; 也许可以在语雀文章标题上加一个前缀表示文章状态;

**Comment by LetTTGACO** [comment]
> 我并不想发布草稿, 但语雀又没有明确的提示哪些文章已发布或未发布, 所以需要一个方式来快速查看文章状态
> 
> 也许可以通过一个命令将文章状态输出; 也许可以在语雀文章标题上加一个前缀表示文章状态;

或许这两个属性配置可以帮到你
```
onlyPublic: false, // 只下载公开文档
onlyPublished: true, //只下载已发布文档
```

**Comment by Jason-Ma-0012** [comment]
问题在于我不知道哪个文章已发布 / 未发布, 我必须将所有文章挨个点一遍发布才行

**Comment by LetTTGACO** [comment]
> 问题在于我不知道哪个文章已发布 / 未发布, 我必须将所有文章挨个点一遍发布才行

语雀之前新增了一个文档自动发布的选项，可以试着用一下。但是之前的文档确实需要手动点一下。
这种一次性的使用/配置，还是建议手动操作下吧。

**Comment by Jason-Ma-0012** [comment]
ok, 这是个折衷的办法, 可以手动打开公开访问权限来发布草稿
