### ISSUE TITLE
能否支持astro平台的静态博客

### ISSUE THREAD

**Issue by xiyuvi** [LetTTGACO/elog#55]
### 描述一下此特性

astro类似与hexo，可以生成静态化博客网站
https://github.com/satnaing/astro-paper

**Comment by LetTTGACO** [comment]
看起来 astro 也是基于 md 渲染的，那当然可以啊，Elog 只是将本地 md 的写作搬到了各种在线平台，只需要按照文档，将在线写作平台的文档下载到本地指定目录就行。
