### ISSUE TITLE
是否考虑一下发布文章撤销的功能

### ISSUE THREAD

**Issue by 3401797899** [LetTTGACO/elog#64]
### 你当前使用的Elog版本

0.13.2

### 描述一下此特性

目前使用FlowUs+Hexo+Vercel进行部署，在FlowUs中我将文章状态从已发布改成进行中之后，重新sync，发现文章并没有被删除。
write部分配置如下：
```javascript
  write: {
    platform: 'flowus',
    flowus: {
      tablePageId: process.env.FLOWUS_TABLE_PAGE_ID,
      filter: { property: 'status', value: '已发布' }
    }
  },
```

**Comment by LetTTGACO** [comment]
https://elog.1874.cool/notion/bry3d3lwe206xuor#sync
可以使用强制同步命令`--force`试试

`elog sync --force`
当需要写作平台的文档和本地文档保持一致时，可添加此命令行参数。例如在写作平台删除文档A后，可通过`--force`参数在本次同步文档时删除本地的文档A。

使用前请注意以下事项：

- 可支持文档删除时强制同步，不支持文档改名后删除改名前的文档
- 你也可以通过elog clean直接清空本地文档后，重新同步文档
- 这个场景比较少见，更推荐手动删除需要处理的本地文档

**Comment by 3401797899** [comment]
我加了--force之后，并不会删除本地的文档。
![image](https://github.com/LetTTGACO/elog/assets/39430235/9310b1cd-4747-46a9-93cd-978314a63467)

这种情况是需要手动删除吗？由于我使用的是Github Action进行部署，手动删除可能不太方便。

如果使用elog clean再sync的话，会清空我原来还没导入FlowUs的文档。

请问还有其他方式可以做到吗？感谢。

**Comment by LetTTGACO** [comment]
看输出日志是因为没有文档，程序提前终止了。

需要确认在`filter: { property: 'status', value: '已发布' }`的筛选条件下是否有符合条件的文档

**Comment by 3401797899** [comment]
在已发布状态下有文章的情况下，是可以正常删除的，感谢。
