### ISSUE TITLE
建议: 支持抓取到多个目录

### ISSUE THREAD

**Issue by Jason-Ma-0012** [LetTTGACO/elog#7]
docusaurus支持文档和博客两种形式:
https://docusaurus.io/zh-CN/docs/blog

默认情况下我将所有正式文章抓取到本地docs目录, 但同时我希望将某个特定目录内的语雀文章抓取到本地blog目录以发布一些不那么正式的短内容, 比如动态, 照片, 视频等

**Comment by LetTTGACO** [comment]
> docusaurus支持文档和博客两种形式: https://docusaurus.io/zh-CN/docs/blog
> 
> 默认情况下我将所有正式文章抓取到本地docs目录, 但同时我希望将某个特定目录内的语雀文章抓取到本地blog目录以发布一些不那么正式的短内容, 比如动态, 照片, 视频等

或许[按目录存放文档](https://elog.1874.cool/notion/xe160pqsumi6bqnz)可以帮到你。
例如：
利用这个能力的话，可以在语雀知识库上新建`docs`目录和`draft`目录，然后把你想发布的内容放到`docs`，把不那么正式的文档放到`draft`目录下。然后按照文档设置按【目录存放文档】，并且配置`outputDir`为根目录。
若如此做，elog会将所有文档存放到两个文档了。

但是这个配置目前有个bug，执行`elog clean`时会将outputDir（也就是根目录）全部删除🤦，这个bug这几天也会修复。
