### ISSUE TITLE
我能否使用nextjs结合这个项目呢？

### ISSUE THREAD

**Issue by white0dew** [LetTTGACO/elog#79]
### 你当前使用的Elog版本

0.14

### 描述一下此特性

我能否使用nextjs结合这个项目呢？
我想有更强的自定义界面。
仅仅只是将elog当作一个【数据库】

**Comment by LetTTGACO** [comment]
ELog 是工具，不是数据库，Elog 的主要功能是导出：https://elog.1874.cool/notion/qa#elog%E4%B8%BB%E8%A6%81%E5%8A%9F%E8%83%BD%E6%98%AF%E6%89%B9%E9%87%8F%E5%AF%BC%E5%87%BA

你可能需要的是隔壁的 [NotionNext](https://github.com/tangly1024/NotionNext)：他就是将 Notion 当做数据库，用 NextJs 渲染页面。当然你也可以将 Elog 结合 NotioNext： Notion 用于数据库，用来书写文档，NotionNext 负责展示，Elog 负责备份 Notion 文档为 markdown 到本地。

**Comment by white0dew** [comment]
> ELog 是工具，不是数据库，Elog 的主要功能是导出：https://elog.1874.cool/notion/qa#elog%E4%B8%BB%E8%A6%81%E5%8A%9F%E8%83%BD%E6%98%AF%E6%89%B9%E9%87%8F%E5%AF%BC%E5%87%BA
> 
> 你可能需要的是隔壁的 [NotionNext](https://github.com/tangly1024/NotionNext)：他就是将 Notion 当做数据库，用 NextJs 渲染页面。当然你也可以将 Elog 结合 NotioNext： Notion 用于数据库，用来书写文档，NotionNext 负责展示，Elog 负责备份 Notion 文档为 markdown 到本地。

感谢回复，我已经寻找到了一种方式，之后会将repo加入最佳实践😊

**Comment by LetTTGACO** [comment]
欢迎实践，期待你的成果

**Comment by LetTTGACO** [comment]
https://github.com/lidelong-0201/next-yuque-elog

貌似 get 到你的点了，你的想法应该是和这位小伙伴类似，自己用 nextjs 渲染 markdown 内容，然后博客的展示样式自己设计。

网站：[www.lidelong.xyz](www.lidelong.xyz)

**Comment by white0dew** [comment]
> https://github.com/lidelong-0201/next-yuque-elog
> 
> 貌似 get 到你的点了，你的想法应该是和这位小伙伴类似，自己用 nextjs 渲染 markdown 内容，然后博客的展示样式自己设计。
> 
> 网站：https://www.lidelong.xyz

最佳实践的repo链接，申请收录：https://github.com/white0dew/OfferNow

**Comment by LetTTGACO** [comment]
1. 没看到部署之后的网站是什么样的，方便部署到某个地方吗，例如 vercel上
2. 缺少最佳实践的文章介绍，最好在 README 或者提供博客url 以供使用者进行配置
希望能提供以上信息

**Comment by white0dew** [comment]
> 非常感谢你的参与，但如果你能提供以下信息，这会更方便社区同学使用
> 
> 1. 没看到部署之后的网站是什么样的，方便部署到某个地方吗，例如 vercel上
> 2. 缺少最佳实践的文章介绍，最好在 README 或者提供博客url 以供使用者进行配置
>    希望能提供以上信息

已补充网站地址～

**Comment by white0dew** [comment]
> 非常感谢你的参与，但如果你能提供以下信息，这会更方便社区同学使用
> 
> 1. 没看到部署之后的网站是什么样的，方便部署到某个地方吗，例如 vercel上
> 2. 缺少最佳实践的文章介绍，最好在 README 或者提供博客url 以供使用者进行配置
>    希望能提供以上信息

附上实现网站：https://offernow.cn/

**Comment by LetTTGACO** [comment]
好的，感谢，我周末会看看，然后添加到最佳实现

**Comment by LetTTGACO** [comment]
已添加到 readme
