### ISSUE TITLE
建议: 为docusaurus生成目录排序

### ISSUE THREAD

**Issue by Jason-Ma-0012** [LetTTGACO/elog#8]
docusaurus支持在front matter中添加sidebar_position属性来给文章排序:
https://docusaurus.io/zh-CN/docs/sidebar/autogenerated#doc-item-metadata

不加排序的情况下会按照文章首字母自动排序, 在中英文混合的情况下会比较混乱, 希望能够自动生成sidebar_position (甚至是_category_.json) 以匹配语雀的排序

**Comment by Jason-Ma-0012** [comment]
当然还有一个选择, 为文件名前缀index进行排序

**Comment by LetTTGACO** [comment]
这个目前[自定义文档处理](https://elog.1874.cool/notion/fe8ywmt999gon12w#formatext-%E5%AD%97%E6%AE%B5%E8%AF%B4%E6%98%8E)可以解决这个问题。

方便的话可以加入微信群细聊

**Comment by LetTTGACO** [comment]
现已支持

**Comment by TypeDreamMoon** [comment]
> 现已支持

请问这个功能如何启用呢
