### ISSUE TITLE
捐赠渠道

### ISSUE THREAD

**Issue by 578223592** [LetTTGACO/elog#80]
### 你当前使用的Elog版本

-

### 描述一下此特性

-

### 附加信息

感谢作者更新,请问有捐赠渠道吗,想请一杯奶茶。虽然还没开始使用，但真觉得是宝藏项目。

**Comment by LetTTGACO** [comment]
哈哈哈，感谢认同，README有的

- 我有两只猫，假如觉得 Elog 让你生活更美好，可以给猫 [喂罐头 🥫](https://1874.cool/cats)。
- 如果你喜欢 Elog，可以在 Github Star，更欢迎推荐给你志同道合的朋友使用。
