### ISSUE TITLE
期待更多的template

### ISSUE THREAD

**Issue by 578223592** [LetTTGACO/elog#82]
### 你当前使用的Elog版本

0.14.0

### 描述一下此特性

RT，期待更多模板。
本人期望的工作流是 语雀 + hexo，模板是语雀 +vitepress。
**本来仿照一个已经成熟的配置：https://github.com/lidelong-0201/next-yuque-elog ，但是无奈尝试后也没有成功。**

感觉配置还是稍显复杂和绕
模板丰富后可能有利于后续推广。

### 附加信息

此外，本人不是前端工作者，有可能是知识欠缺导致。
如果作者没有兴趣开发 语雀 + hexo 的模板，请随意关闭此issue

**Comment by LetTTGACO** [comment]
README 中有一个开箱即用的版本，感觉是你想要的，而且不需要怎么配置，可以试试看

[语雀 + Elog + VitePress + GitHub Actions + Vercel 文档站点解决方案](https://github.com/elog-x/yuque-vitepress) 👉 [Yuque-Vitepress](https://yuque-vitepress.vercel.app/)

**Comment by LetTTGACO** [comment]
看错了，你想要语雀 + hexo 的话，晚点我搞一个哈

**Comment by LetTTGACO** [comment]
他这个可不是 hexo 的next 主题，也没有用 hexo，他是用 nextjs 重新写的主题，正如他描述的那样：语雀作为博客后台，elog生成语雀内容，nextjs+mdx进行渲染，cloudflare+vercel搭建

1. 如果你想基于他的自己写的主题，进行模版复刻，我可以帮忙
2. 如果你想基于 hexo 的生态打造，可以提供你想要的hexo主题。例如这个，就是 hexo 的[Butterfly](https://github.com/jerryc127/hexo-theme-butterfly)主题，我我用 notion 就是搭建的这个，如果要换到语雀，也很简单。稍微改一下配置就行

**Comment by 578223592** [comment]
> 他这个可不是 hexo 的next 主题，也没有用 hexo，他是用 nextjs 重新写的主题，正如他描述的那样：语雀作为博客后台，elog生成语雀内容，nextjs+mdx进行渲染，cloudflare+vercel搭建
> 
> 1. 如果你想基于他的自己写的主题，进行模版复刻，我可以帮忙
> 2. 如果你想基于 hexo 的生态打造，可以提供你想要的hexo主题。例如[这个](https://notion-hexo.vercel.app/)，就是 hexo 的[Butterfly](https://github.com/jerryc127/hexo-theme-butterfly)主题，我我用 notion 就是搭建的这个，如果要换到语雀，也很简单。稍微改一下配置就行

明白你的意思了。
我认为那个博主写的主题或者hexo的[next主题](https://github.com/next-theme/hexo-theme-next)，亦或是[hugo中类似的的next主题](https://hugo-next.eu.org/) 都是比较不错的。

我不是很清楚几种方案的工作量有什么区别，这三个中我倾向于工作量最少的方案。

**Comment by LetTTGACO** [comment]
从工作量的考虑来说，hexo 的[next主题](https://github.com/next-theme/hexo-theme-next)应该是最简单的。我就用这个做模版吧，快的话今晚会搞定

**Comment by 578223592** [comment]
> 从工作量的考虑来说，hexo 的[next主题](https://github.com/next-theme/hexo-theme-next)应该是最简单的。我就用这个做模版吧，快的话今晚会搞定

@LetTTGACO So thanks,and look forward it.

**Comment by LetTTGACO** [comment]
https://github.com/elog-x/yuque-hexo

搭了个架子，你跟着 README 走一遍就行，主要是配置.elog.env， 写上你自己的语雀相关账号文档库信息就行。一些细节明天了完善。

**Comment by LetTTGACO** [comment]
[语雀 + Elog + Hexo + GitHub Actions + Vercel 博客解决方案](https://github.com/elog-x/yuque-hexo) 👉 [Yuque-Hexo](https://yuque-hexo.vercel.app/)

基本已完善，可以参考Github README 或者示例网站的快速开始进行操作

**Comment by 578223592** [comment]
> [语雀 + Elog + Hexo + GitHub Actions + Vercel 博客解决方案](https://github.com/elog-x/yuque-hexo) 👉 [Yuque-Hexo](https://yuque-hexo.vercel.app/)
> 
> 基本已完善，可以参考Github README 或者示例网站的快速开始进行操作

@LetTTGACO  非常感谢，这周在完成毕业答辩，所以没有来得及尝鲜，目前尝试了一下，已经基本配置成功了，感谢感谢。

> 不过目前我发现只能手动同步，没法自动同步（serverless api也不行），已经在https://github.com/elog-x/yuque-hexo/issues/new中提issue了

这个issue我关闭了，再次感谢。
