### ISSUE TITLE
能不能支持多吉云的sdk啊，https://docs.dogecloud.com/oss/api-access-token?id=nodejs

### ISSUE THREAD

**Issue by white0dew** [LetTTGACO/elog#83]
### 你当前使用的Elog版本

0.14

### 描述一下此特性

能不能支持多吉云的sdk啊，https://docs.dogecloud.com/oss/api-access-token?id=nodejs

### 附加信息

能不能支持多吉云的sdk啊，https://docs.dogecloud.com/oss/api-access-token?id=nodejs

**Comment by LetTTGACO** [comment]
我目前没有用多吉云，你可以参考[plugin-img-r2](https://github.com/LetTTGACO/elog/tree/master/plugins/plugin-img-r2#readme)自行实现。

或者你方便的话提供一个临时的 AK 发邮件（me@mail.1874.cool）给我，我用于开发测试，后续你再更改密钥

**Comment by white0dew** [comment]
> 我目前没有用多吉云，你可以参考[plugin-img-r2](https://github.com/LetTTGACO/elog/tree/master/plugins/plugin-img-r2#readme)自行实现。
> 
> 或者你方便的话提供一个临时的 AK 发邮件（[me@mail.1874.cool](mailto:me@mail.1874.cool)）给我，我用于开发测试，后续你再更改密钥
已经解决，并且我实现啦语雀写作（自动生成导航栏）+ Elog同步 + ContentLayer + NextJs 服务端渲染 +  +Docker部署

**Comment by white0dew** [comment]
> > 我目前没有用多吉云，你可以参考[plugin-img-r2](https://github.com/LetTTGACO/elog/tree/master/plugins/plugin-img-r2#readme)自行实现。
> > 或者你方便的话提供一个临时的 AK 发邮件（[me@mail.1874.cool](mailto:me@mail.1874.cool)）给我，我用于开发测试，后续你再更改密钥
> > 已经解决，并且我实现啦语雀写作（自动生成导航栏）+ Elog同步 + ContentLayer + NextJs 服务端渲染 +  +Docker部署

最佳实践的repo链接，申请收录：https://github.com/white0dew/OfferNow

**Comment by LetTTGACO** [comment]
非常感谢你的参与，但我看你是把 多吉云的SDK写在博客仓库的，也并没有相应的配置文档说明

建议：抽离成你自己单独的多吉云SDK仓库，并提供相应的配置文档，我会收录到此仓库中：[awesome-elog](https://github.com/elog-x/awesome-elog)，你也可以自行提交 PR 到该仓库进行说明和配置

**Comment by white0dew** [comment]
好的，这周末我会梳理一下文档。
