### ISSUE TITLE
语雀文档不会删除

### ISSUE THREAD

**Issue by white0dew** [LetTTGACO/elog#86]
### 你当前使用的Elog版本

0.14

### Elog配置文件

```javascript
语雀文档不会删除未使用的文件夹以及文件，会造成冗余的内容
```

### 发生了什么？

语雀文档不会删除未使用的文件夹以及文件，会造成冗余的内容

### Elog错误日志

```shell
语雀文档不会删除未使用的文件夹以及文件，会造成冗余的内容
```

### 附加信息

语雀文档不会删除未使用的文件夹以及文件，会造成冗余的内容

**Comment by LetTTGACO** [comment]
我理解你这种场景是出现在：
尚未完全整理好语雀写作平台的目录结构，在写作的过程中较为经常会出现文件夹名称变动，所以导致同步到本地时会出现以往创建的文件夹出现冗余的情况。

可以尝试给 elog sync 命令增加 `--force`试一试，它会处理删除的文档，但并不一定会处理删除的文件夹。
说明文档：https://elog.1874.cool/notion/bry3d3lwe206xuor#force-%E8%AF%B4%E6%98%8E

Elog 更希望用户能提前清晰规划好写作平台的目录结构，不要一直变动目录结构和重命名文件夹和文档。
当然如果确实需要变动，建议直接手动删除或运行 elog clean 进行清理后重新同步，这样的做法更有效率。
