### ISSUE TITLE
语雀文档的表现不一致

### ISSUE THREAD

**Issue by white0dew** [LetTTGACO/elog#88]
### 你当前使用的Elog版本

最新

### Elog配置文件

```javascript
最新
```

### 发生了什么？

我发现语雀文档里的表现和使用手册里不一致：
1、如果是文本绘图，转换之后直接消失
2、如果是画板，那么转换之后就是图片
在这里完全相反的：https://elog.1874.cool/yuque-pwd/yuque-example

**Comment by LetTTGACO** [comment]
请提供 elog.config.js配置文件，该文件没有任何敏感信息，请放心提供

**Comment by white0dew** [comment]
> 请提供 elog.config.js配置文件，该文件没有任何敏感信息，请放心提供

const r2 = require("@elog/plugin-img-r2");
const dogeCloudUploader = require("./elog-doge-upload");

module.exports = {
  write: {
    platform: "yuque-pwd",
    // Token 模式（需要语雀超级会员）
    yuque: {
      token: process.env.YUQUE_TOKEN,
      login: process.env.YUQUE_LOGIN,
      repo: process.env.YUQUE_REPO,
      onlyPublic: false,
      onlyPublished: true,
    },
    // 账号密码模式
    "yuque-pwd": {
      username: process.env.YUQUE_USERNAME,
      password: process.env.YUQUE_PASSWORD,
      login: process.env.YUQUE_LOGIN,
      repo: process.env.YUQUE_REPO,
      onlyPublic: false,
      onlyPublished: true,
      linebreak: false, // 会有问题
    },
  },
  deploy: {
    platform: "local",
    local: {
      outputDir: "./docs/doc",
      filename: "urlname",
      format: "markdown",
      catalog: true,
      formatExt: "./elog.format.js",
      frontMatter: {
        enable: true,
      },
    },
  },
  image: {
    enable: true,
    plugin: "./elog-doge-upload.js", // 使用自己的本地插件路径，放置在和elog.config.js同级目录
    // enableForExt: true,
    // plugin: r2, // 使用 npm 插件
    plugin: dogeCloudUploader, // 使用 npm 插件
    // plugin: require("r2"), // 使用 npm 插件
    dogeCloudUploader: {
      accessKeyId: process.env.R2_ACCESSKEYID,
      secretAccessKey: process.env.R2_SECRET_ACCESSKEY,
      bucket: process.env.R2_BUCKET,
      endpoint: process.env.R2_ENDPOINT,
      host: process.env.R2_HOST,
      prefixKey: "elog-offer-now",
    },
    // platform: "oss",

    // local: {
    //   outputDir: "./docs/images",
    //   pathFollowDoc: true,
    // },
  },
};

**Comment by white0dew** [comment]
> 请提供 elog.config.js配置文件，该文件没有任何敏感信息，请放心提供

你好，请问有结论了吗，还是说语雀文档写错了啊

**Comment by white0dew** [comment]
已解决，参考解决方案：https://offernow.cn/s/self_improve/own_web/ybyfy5goc6dp2d87

**Comment by LetTTGACO** [comment]
感谢，我周末会看看，最近比较忙
