### ISSUE TITLE
在导出Notion文章时添加了错误的转义符号

### ISSUE THREAD

**Issue by AndyBlocker** [LetTTGACO/elog#89]
### 你当前使用的Elog版本

0.14.1

### Elog配置文件

```javascript
module.exports = {
  write: {
    platform: 'notion',
    notion: {
      token: process.env.NOTION_TOKEN,
      databaseId: process.env.NOTION_DATABASE_ID,
      filter:  {property: 'status', select: {equals: '已发布'}},
    }
  },
  deploy: {
    platform: 'local',
    local: {
      outputDir: './src/content/blog',
      filename: 'title',
      format: 'matter-markdown',
      frontMatter: {
        enable : true,
        timeFormat: true, 
        include: ['title', 'pubDatetime', 'description', 'tags'],
      },
      formatExt: 'elog.format.js'
    }
  },
  image: {
    enable: true,
    platform: 'local',
    local: {
      outputDir: './public/images',
      prefixKey: '/images',
      pathFollowDoc: false,
    }
  }
}
```

### 发生了什么？

在导出https://polydactyl-kidney-018.notion.site/SpikingJelly-An-open-source-machine-learning-infrastructure-platform-for-spike-based-intelligence-57439434875e4df29c1a330598f18976
这个页面的文章时，elog在大部分公式中错误地添加了反斜杠（如大部分公式中的[]、_前，删除了公式中的\\换行或修改为\0）。

**Comment by LetTTGACO** [comment]
1. 公式可能需要博客平台相对应的插件支持，一部分博客会无法识别导致报错，可以检查一下你的博客平台
2.notion to md 为第三方库， 我需要复现并检查一下看是否需要更新这个库的版本。

目前还是建议先从 1 中寻找支持，elog 本身是没有对 md 做处理的，我这边尝试复现解决一下。

方便贴一下出问题的那段公式的 md 文档内容吗？

**Comment by AndyBlocker** [comment]
> 1. 公式可能需要博客平台相对应的插件支持，一部分博客会无法识别导致报错，可以检查一下你的博客平台
>    2.notion to md 为第三方库， 我需要复现并检查一下看是否需要更新这个库的版本。
> 
> 目前还是建议先从 1 中寻找支持，elog 本身是没有对 md 做处理的，我这边尝试复现解决一下。
> 
> 方便贴一下出问题的那段公式的 md 文档内容吗？

平台本身渲染是没有问题的，在使用elog导出其他文章的时候也没有遇到这个问题；导出的文章在上面的链接中，直接复制得到的内容如下：
[file.md](https://github.com/user-attachments/files/16067047/file.md)

**Comment by LetTTGACO** [comment]
你用的什么博客平台

**Comment by AndyBlocker** [comment]
> 你用的什么博客平台



> 你用的什么博客平台



> 你用的什么博客平台

Astro，所以实际上只用到了导出markdown的功能；

加粗的问题在之前用halo的时候也遇到过

**Comment by LetTTGACO** [comment]
我也用的Astro
网址：https://blog.1874.cool
Github：https://github.com/LetTTGACO/blog.1874.cool

我这两天排查一下

**Comment by AndyBlocker** [comment]
最近的同步中好像没有这个问题了，可能是notion2md修复了这个bug？
