### ISSUE TITLE
请问用 notion 部署的话, notion 的图片是要用三方图床吗?

### ISSUE THREAD

**Issue by 668168** [LetTTGACO/elog#9]

**Comment by LetTTGACO** [comment]
可以直接下载到本地，当然也可以存到第三方图床
目前支持以下第三方图床
- 腾讯云 COS
- 阿里云 OSS
- Github 图床
- 七牛云
- 又拍云

**Comment by 668168** [comment]
谢谢答疑,
意思是 notion 本身的图片无法显示?

**Comment by LetTTGACO** [comment]
> 谢谢答疑, 意思是 notion 本身的图片无法显示?

Notion的图片链接会有访问有效期，一般是一个小时，过期就不能访问了。所以建议下载到本地或者上传到第三方图床

![image](https://github.com/LetTTGACO/elog/assets/37357188/efe53716-9110-4c7f-8a37-0b0d8b446ef0)

**Comment by 668168** [comment]
谢谢说明. close issue, please
