### ISSUE TITLE
增加友好信息提示：对飞书配置错误添加友好提示

### ISSUE THREAD

**Issue by 0xSparks** [LetTTGACO/elog#93]
### 你当前使用的Elog版本

0.14.2

### 描述一下此特性

``` log
.nvmd\versions\20.15.0\node_modules\@elog\cli\node_modules\@feishux\api\dist\api.js:198
result.push(...res.items);

TypeError: Cannot read properties of undefined (reading 'items')
```
粗心大意没给群聊设为协作者，也没给群聊添加为成员/管理员，出现了这个错误，建议加个`out.err()`友好提示🐱

**Comment by LetTTGACO** [comment]
感谢，已增加友好提示

由于本次改动只涉及 elog 依赖的feishu 相关包，并未改动到 elog 本体。更新办法
1. 如果你是使用 package.json 进行安装和并使用 npm script 运行 elog 命令，请删除 node_modules 和 package-lock.json 重新安装 elog 即可
2. 如果你是将 elog 安装到全局环境（`npm i @elog/cli -g`） 请卸载elog（`npm uninstall -g @elog/cli`） 后重新安装elog 即可
